apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  TEST_ENV: test

---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: busybox
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ] # print env var
      envFrom:
        - configMapRef:
            name: test-config
